name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version input
        id: vars
        run: echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Append common_tools.sh to each script
        run: |
          # Store content of common_tools.sh removing the shebang line into a variable
            common_tools_content=$(tail -n +2 scripts/common_tools.sh)

            # Append common_tools.sh content to each script, excluding common_tools.sh itself
            for script in scripts/*.sh; do
              if [ "$script" != "scripts/common_tools.sh" ]; then
                echo "$common_tools_content" >> $script
              fi
            done

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          artifacts: "scripts/*.sh"
